### ISSUE TITLE
Ignore requested reviewers who haven't actually reviewed

### ISSUE THREAD

**Issue by swissspidy** [WordPress/props-bot-action#140]
### Problem

Over at https://github.com/WordPress/plugin-check we have set up code owners so that a bunch of people are automatically requested to perform code reviews. After N approvals a PR can be merged.

The problem is that only some people actually do a review, but props bot adds a `Co-authored-by` line for all of them regardless, even if they didn't do anything.

### Feature Request

Do not include people who haven't actually reviewed.

### Workaround

Manually clean up `Co-authored-by` lines for people who didn't actually review.

### Repository

https://github.com/WordPress/plugin-check

**Comment by desrosj** [comment]
@swissspidy do you happen to have a PR handy that shows this behavior? I'm having a bit of trouble reproducing.

I've tested the same queries used by Props Bot in the [GraphQL explorer](https://docs.github.com/en/graphql/overview/explorer) on various PRs and I can't get a user who only had a review request to be returned.

If I had to guess, the contributor may have engaged with a linked issue in some way. All participants for any linked issue are currently pulled in as well.

**Comment by swissspidy** [comment]
Oh, maybe it was that. I tried to find the PR again, but couldn't. I'll reopen if I spot it again.

Thanks & sorry for the false alarm.

**Comment by desrosj** [comment]
No worries! Thanks for working to improve this tool to ensure proper attribution occurs!
