### ISSUE TITLE
Exclude PR author from the list

### ISSUE THREAD

**Issue by noisysocks** [WordPress/props-bot-action#46]
### Description

I wouldn't expect to see my own name in the list of props here.

https://github.com/WordPress/gutenberg/pull/58580

<img width="911" alt="Screenshot 2024-02-02 at 10 54 18" src="https://github.com/WordPress/props-bot-action/assets/612155/89f51d12-6353-479c-8bef-5bca305b0ada">

### Version

v1

**Comment by desrosj** [comment]
So initially I excluded the author from the list. But I found there was one inconsistency.

The name and email used in the commit message/log is whatever the person had set in their local configuration when they made the commits. This means that their name could be anything, and their email could also be anything.

When parsing the git log that would make it impossible to know which GitHub user the commit belongs to without some manually intervention, Which puts us right back to the process that was followed until this was introduced (match contributors to .org accounts through some research and name/email matching).

If we were using the GitHub API to pull in and parse props, that would likely work, provided whatever email the person used is associated with their account (I've seen some instances where it's not).

By including them in the list, it allows a script to parse out all contributors without worrying about having to try to to guess or match a contributor's w.org account.

If this is incorrect or if there's something we've missed, I'd be more than happy to omit the author's name. That's how the wordpress-develop log gets parsed, but the committees email is always user@git.wordpress.org from the git-scan sync and mirror.

**Comment by desrosj** [comment]
Wanted to triple check this, and confirmed the above is true. Here is a merge commit message where you left yourself out of the list:

```
commit b859f54ccf1ae1c8d1296ddf93f23c614cb2d240
Author: Robert Anderson <robert@noisysocks.com>
Date:   Fri Feb 2 11:57:05 2024 +1100

    Font Library: Show 'Add fonts' button when there are no fonts installed (#58580)

    Co-authored-by: ramonjd <ramonopoly@git.wordpress.org>
```

You can see your name and email are listed as configured by whatever you used to author that commit. But someone could set it to anything at all. From a .org perspective, we could likely match your account in this example provided your email is the same as your .org account, but I've seen some contributors use several different emails when authoring commits.

I'm going to close this out, but I've [added a link to this explanation in the handbook page](https://make.wordpress.org/core/handbook/best-practices/contributor-attribution-props/#github-specific-notes). Previously it only mentioned authors should remain and not why.

**Comment by noisysocks** [comment]
Fair enough thanks Jonathan.
