### ISSUE TITLE
Add the Issue author to the props list

### ISSUE THREAD

**Issue by Mamaduka** [WordPress/props-bot-action#49]
### Problem

Unlike Trac, the people who report issues for Gutenberg don't get props when the issue is fixed or resolved.

### Feature Request

When a PR has a linked issue, include its author in the props list.

**Comment by desrosj** [comment]
This should be happening currently, @Mamaduka. Is there a PR with an attached issue where you're not seeing this work correctly?

**Comment by Mamaduka** [comment]
Oh, sorry for the false alarm. It looks like a few examples I checked had the same author of Issue/PR.

I can confirm it is working correctly. Example -https://github.com/WordPress/gutenberg/pull/58609.

**Comment by desrosj** [comment]
Great! No worries, thanks for paying close attention to help refine this new tool!
