### ISSUE TITLE
The props bot sometimes adds repetitive comments rather than updating the existing comment

### ISSUE THREAD

**Issue by andrewserong** [WordPress/props-bot-action#54]
### Description

In a particular Gutenberg PR, the props bot appears to be adding repetitive comments after each commit or comment, rather than checking and updating the existing comment.

For example: https://github.com/WordPress/gutenberg/pull/57841#issuecomment-1926007588 — note that alternating comments / commits appear to be between a comment or commit by a user, and then a new comment from the props bot.

Is it possible that the props bot is unable to find its existing comment to update, for some reason?

Another idea from @tellthemachines: could this be to do with this PR originating from before the props bot was added?

### Version

trunk

### Workflow file

https://github.com/WordPress/gutenberg/blob/trunk/.github/workflows/props-bot.yml

### Link

https://github.com/WordPress/gutenberg/pull/57841

**Comment by desrosj** [comment]
I think that this is due to the [upper limit being 100](https://octokit.github.io/rest.js/v20#issues-list-comments) when querying the REST API to look for a previous comment.

Looking at the action, this will need to be a different solution than #53 because those queries utilize the GraphQL API.
