### ISSUE TITLE
Add a comment suggesting unconnected users create/link their wp.org account

### ISSUE THREAD

**Issue by desrosj** [WordPress/props-bot-action#8]
When a GitHub user makes a contribution and has not connected a WP.org account, the bot should also ping that contributor with a polite explanation of the benefits of connecting their accounts.

This likely can just be included in the same comment at the end, but we should confirm that users receive pings when added to a comment in an edit.

**Comment by jeffpaul** [comment]
Initial copy for this might as well start with the copy from the Gutenberg-to-WP.org action and tweak for the needs here.
