### ISSUE TITLE
Props bot comment not updated if it is a PR from a forked repository

### ISSUE THREAD

**Issue by t-hamano** [WordPress/props-bot-action#91]
### Description

In the Gutenberg project, when a PR is submitted from a forked repository, the Props bot comment may not be updated even if you review or comment on the PR.

It doesn't seem to be consistently reproduced, but for example, in the PR below, no reviewer or commenter is added to the Props bot.

- https://github.com/WordPress/gutenberg/pull/59973
- https://github.com/WordPress/gutenberg/pull/59862
- https://github.com/WordPress/gutenberg/pull/59887
- https://github.com/WordPress/gutenberg/pull/59720

### Version

trunk

**Comment by Mamaduka** [comment]
I've noticed that same issue.

P.S. The "Flaky tests" bot's reports also have a similar problem. Here are the details if they might be helpful - https://github.com/WordPress/gutenberg/pull/46988.

**Comment by desrosj** [comment]
This seems like a duplicate of #57.

**Comment by t-hamano** [comment]
Oh, I reported the exact same thing before 😅 I would like to close this issue.
